server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: admin
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

