server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/user_service
    username: postgres
    password: postgres
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format-sql: true
          use_sql_comments: true
      hibernate:
        ddl-auto: update

