version: '3.8'
services:
  postgres-db-server:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: user_service
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/database-init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - ecommerce_network_user_service

  liquibase-server:
    image: liquibase/liquibase
    container_name: liquibase_container
    depends_on:
      - postgres-db-server
    restart: always
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
      - ./wait-for-it.sh:/liquibase/wait-for-it.sh
    command:
      - sh
      - -c
      - "/liquibase/wait-for-it.sh -t 120 postgres-db-server 5432 -- \
             liquibase --changeLogFile=/liquibase/changelog/db.changelog-master.xml \
             --url=jdbc:postgresql://postgres-db-server:5432/user_service \
             --username=postgres --password=postgres update"
    networks:
      - ecommerce_network_user_service

networks:
  ecommerce_network_user_service: