version: '3.8'
services:
  postgres-db-server:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: user_service
    ports:
      - "5432:5432"
    networks:
      - ecommerce_network_user_service
    volumes:
      - ./src/config/local-database-init:/docker-entrypoint-initdb.d
  pgadmin-server:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db-server
    networks:
      - ecommerce_network_user_service
  liquibase-server:
    container_name: liquibase_container
    image: liquibase/liquibase
    depends_on:
      - postgres-db-server
    command: ["--changeLogFile=db/changelog/db.changelog-master.xml", "--url=jdbc:postgresql://postgres_container:5432/user_service", "--username=postgres", "--password=postgres", "update"]
    volumes:
      - ./src/main/resources/db/changelog:/docker-entrypoint-initdb.
    networks:
      - ecommerce_network_user_service

networks:
  ecommerce_network_user_service: